name: DependaBot Update Check via Ruby

on: [pull_request]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Build and test with Rake
      run: |
        gem install bundler
        bundle config set no-cache 'true'
        bundle config set path 'vendor/bundle'
        bundle install --jobs 12 --retry 3
    - name: Test Jekyll build
      run: bundle exec jekyll build

  auto-merge:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: auto-merge
        uses: ridedott/dependabot-auto-merge-action@master
        with:
          GITHUB_TOKEN: ${{ secrets.GitOAUTHToken2 }}
