name: Merge Upstream Updates

on:
  workflow_dispatch:
  schedule:
    # Run at 03:00am, once a week, every month
    - cron: '0 3 5,12,21,28 1-12 ?'

jobs:

  upstream:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'master'
        fetch-depth: '0'
    - name: Set up Ruby 2.7
      uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - name: Pull everything from Upstream except lockfile
      run: |
        git config --global user.name "rokibhasansagar"
        git config --global user.email "rokibhasansagar2014@outlook.com"
        git pull https://github.com/jimeh/jimeh.github.io master --ff -Xtheirs --no-edit
        rm Gemfile.lock && git rm -f Gemfile.lock
    - name: Install & Update dependencies
      run: |
        gem install bundler
        bundle update --bundler --jobs 8
        bundle config set no-cache 'true'
        bundle config set path 'vendor/bundle'
        bundle install --jobs 12 --retry 3
        bundle update --all --jobs 12
    - name: Test Jekyll build
      run: bundle exec jekyll build
    - name: Add and push the changes
      run: |
        if git status --porcelain | grep Gemfile; then
          git add "Gem*"
          git config --local user.email "support@dependabot.com"
          git config --local user.name "dependabot[bot]"
          git commit -m "Force Cron Update"
          git push -f origin master
          echo "Updated the master branch"
        else
          echo "Retrying a force push"
          git push -f origin master
        fi
